/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef APPLIFIERCROSSPROMOTION_AUTODEFS_H
#define APPLIFIERCROSSPROMOTION_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APPLIFIERCROSSPROMOTION_NAME "ApplifierCrossPromotion"
#define S3E_EXT_APPLIFIERCROSSPROMOTION_HASH 0xbf725632

#endif /* !APPLIFIERCROSSPROMOTION_AUTODEFS_H */
