/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "ApplifierCrossPromotion_autodefs.h"
#include "s3eEdk.h"
#include "ApplifierCrossPromotion.h"
//Declarations of Init and Term functions
extern s3eResult ApplifierCrossPromotionInit();
extern void ApplifierCrossPromotionTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult ApplifierCrossPromotionInitialize_wrap(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionInitialize"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionInitialize, 5, applifierID, orientationHomeButtonDown, orientationHomeButtonRight, orientationHomeButtonLeft, orientationHomeButtonUp);
}

static bool ApplifierCrossPromotionShowBanner_wrap(int positionX, int positionY)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionShowBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionShowBanner, 2, positionX, positionY);
}

static bool ApplifierCrossPromotionHideBanner_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionHideBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionHideBanner, 0);
}

static bool ApplifierCrossPromotionPrepareFeaturedGames_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionPrepareFeaturedGames"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionPrepareFeaturedGames, 0);
}

static bool ApplifierCrossPromotionPrepareInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionPrepareInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionPrepareInterstitial, 0);
}

static bool ApplifierCrossPromotionIsFeaturedGamesReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionIsFeaturedGamesReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionIsFeaturedGamesReady, 0);
}

static bool ApplifierCrossPromotionIsInterstitialReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionIsInterstitialReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionIsInterstitialReady, 0);
}

static bool ApplifierCrossPromotionShowFeaturedGames_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionShowFeaturedGames"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionShowFeaturedGames, 0);
}

static bool ApplifierCrossPromotionShowInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionShowInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionShowInterstitial, 0);
}

static bool ApplifierCrossPromotionPauseRenderer_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionPauseRenderer"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionPauseRenderer, 0);
}

static bool ApplifierCrossPromotionMoveBanner_wrap(int x, int y)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionMoveBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionMoveBanner, 2, x, y);
}

static bool ApplifierCrossPromotionShowCustomInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionShowCustomInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionShowCustomInterstitial, 0);
}

static bool ApplifierCrossPromotionPrepareCustomInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionPrepareCustomInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionPrepareCustomInterstitial, 0);
}

static bool ApplifierCrossPromotionIsCustomInterstitialReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionIsCustomInterstitialReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionIsCustomInterstitialReady, 0);
}

static bool ApplifierCrossPromotionShowAnimated_wrap(int corner)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionShowAnimated"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionShowAnimated, 1, corner);
}

static bool ApplifierCrossPromotionPrepareAnimated_wrap(int corner)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionPrepareAnimated"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionPrepareAnimated, 1, corner);
}

static bool ApplifierCrossPromotionIsAnimatedReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: ApplifierCrossPromotionIsAnimatedReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ApplifierCrossPromotionIsAnimatedReady, 0);
}

#define ApplifierCrossPromotionInitialize ApplifierCrossPromotionInitialize_wrap
#define ApplifierCrossPromotionShowBanner ApplifierCrossPromotionShowBanner_wrap
#define ApplifierCrossPromotionHideBanner ApplifierCrossPromotionHideBanner_wrap
#define ApplifierCrossPromotionPrepareFeaturedGames ApplifierCrossPromotionPrepareFeaturedGames_wrap
#define ApplifierCrossPromotionPrepareInterstitial ApplifierCrossPromotionPrepareInterstitial_wrap
#define ApplifierCrossPromotionIsFeaturedGamesReady ApplifierCrossPromotionIsFeaturedGamesReady_wrap
#define ApplifierCrossPromotionIsInterstitialReady ApplifierCrossPromotionIsInterstitialReady_wrap
#define ApplifierCrossPromotionShowFeaturedGames ApplifierCrossPromotionShowFeaturedGames_wrap
#define ApplifierCrossPromotionShowInterstitial ApplifierCrossPromotionShowInterstitial_wrap
#define ApplifierCrossPromotionPauseRenderer ApplifierCrossPromotionPauseRenderer_wrap
#define ApplifierCrossPromotionMoveBanner ApplifierCrossPromotionMoveBanner_wrap
#define ApplifierCrossPromotionShowCustomInterstitial ApplifierCrossPromotionShowCustomInterstitial_wrap
#define ApplifierCrossPromotionPrepareCustomInterstitial ApplifierCrossPromotionPrepareCustomInterstitial_wrap
#define ApplifierCrossPromotionIsCustomInterstitialReady ApplifierCrossPromotionIsCustomInterstitialReady_wrap
#define ApplifierCrossPromotionShowAnimated ApplifierCrossPromotionShowAnimated_wrap
#define ApplifierCrossPromotionPrepareAnimated ApplifierCrossPromotionPrepareAnimated_wrap
#define ApplifierCrossPromotionIsAnimatedReady ApplifierCrossPromotionIsAnimatedReady_wrap

#endif

void ApplifierCrossPromotionRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[18];
    funcPtrs[0] = (void*)ApplifierCrossPromotionInitialize;
    funcPtrs[1] = (void*)ApplifierCrossPromotionShowBanner;
    funcPtrs[2] = (void*)ApplifierCrossPromotionHideBanner;
    funcPtrs[3] = (void*)ApplifierCrossPromotionPrepareFeaturedGames;
    funcPtrs[4] = (void*)ApplifierCrossPromotionPrepareInterstitial;
    funcPtrs[5] = (void*)ApplifierCrossPromotionIsFeaturedGamesReady;
    funcPtrs[6] = (void*)ApplifierCrossPromotionIsInterstitialReady;
    funcPtrs[7] = (void*)ApplifierCrossPromotionShowFeaturedGames;
    funcPtrs[8] = (void*)ApplifierCrossPromotionShowInterstitial;
    funcPtrs[9] = (void*)ApplifierCrossPromotionPauseRenderer;
    funcPtrs[10] = (void*)ApplifierCrossPromotionMoveBanner;
    funcPtrs[11] = (void*)ApplifierCrossPromotionGetPlatform;
    funcPtrs[12] = (void*)ApplifierCrossPromotionShowCustomInterstitial;
    funcPtrs[13] = (void*)ApplifierCrossPromotionPrepareCustomInterstitial;
    funcPtrs[14] = (void*)ApplifierCrossPromotionIsCustomInterstitialReady;
    funcPtrs[15] = (void*)ApplifierCrossPromotionShowAnimated;
    funcPtrs[16] = (void*)ApplifierCrossPromotionPrepareAnimated;
    funcPtrs[17] = (void*)ApplifierCrossPromotionIsAnimatedReady;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[18] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("ApplifierCrossPromotion", funcPtrs, sizeof(funcPtrs), flags, ApplifierCrossPromotionInit, ApplifierCrossPromotionTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int ApplifierCrossPromotionStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&ApplifierCrossPromotionRegisterExt;
    return 0;
}

int g_ApplifierCrossPromotionVal = ApplifierCrossPromotionStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    ApplifierCrossPromotionRegisterExt();
}
#endif

#endif
