/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "ApplifierCrossPromotion.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*init_t)(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp);
typedef       bool(*showBanner_t)(int positionX, int positionY);
typedef       bool(*hideBanner_t)();
typedef       bool(*prepareFeaturedGames_t)();
typedef       bool(*prepareInterstitial_t)();
typedef       bool(*isFeaturedGamesReady_t)();
typedef       bool(*isInterstitialReady_t)();
typedef       bool(*showFeaturedGames_t)();
typedef       bool(*showInterstitial_t)();
typedef       bool(*pauseRenderer_t)();

/**
 * struct that gets filled in by ApplifierCrossPromotionRegister
 */
typedef struct ApplifierCrossPromotionFuncs
{
    init_t m_init;
    showBanner_t m_showBanner;
    hideBanner_t m_hideBanner;
    prepareFeaturedGames_t m_prepareFeaturedGames;
    prepareInterstitial_t m_prepareInterstitial;
    isFeaturedGamesReady_t m_isFeaturedGamesReady;
    isInterstitialReady_t m_isInterstitialReady;
    showFeaturedGames_t m_showFeaturedGames;
    showInterstitial_t m_showInterstitial;
    pauseRenderer_t m_pauseRenderer;
} ApplifierCrossPromotionFuncs;

static ApplifierCrossPromotionFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xbf725632, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: ApplifierCrossPromotion");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xbf725632, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool ApplifierCrossPromotionAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult init(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[0] func: init"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_init(applifierID, orientationHomeButtonDown, orientationHomeButtonRight, orientationHomeButtonLeft, orientationHomeButtonUp);
}

bool showBanner(int positionX, int positionY)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[1] func: showBanner"));

    if (!_extLoad())
        return false;

    return g_Ext.m_showBanner(positionX, positionY);
}

bool hideBanner()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[2] func: hideBanner"));

    if (!_extLoad())
        return false;

    return g_Ext.m_hideBanner();
}

bool prepareFeaturedGames()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[3] func: prepareFeaturedGames"));

    if (!_extLoad())
        return false;

    return g_Ext.m_prepareFeaturedGames();
}

bool prepareInterstitial()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[4] func: prepareInterstitial"));

    if (!_extLoad())
        return false;

    return g_Ext.m_prepareInterstitial();
}

bool isFeaturedGamesReady()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[5] func: isFeaturedGamesReady"));

    if (!_extLoad())
        return false;

    return g_Ext.m_isFeaturedGamesReady();
}

bool isInterstitialReady()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[6] func: isInterstitialReady"));

    if (!_extLoad())
        return false;

    return g_Ext.m_isInterstitialReady();
}

bool showFeaturedGames()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[7] func: showFeaturedGames"));

    if (!_extLoad())
        return false;

    return g_Ext.m_showFeaturedGames();
}

bool showInterstitial()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[8] func: showInterstitial"));

    if (!_extLoad())
        return false;

    return g_Ext.m_showInterstitial();
}

bool pauseRenderer()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[9] func: pauseRenderer"));

    if (!_extLoad())
        return false;

    return g_Ext.m_pauseRenderer();
}
