/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "ApplifierCrossPromotion_autodefs.h"
#include "s3eEdk.h"
#include "ApplifierCrossPromotion.h"
//Declarations of Init and Term functions
extern s3eResult ApplifierCrossPromotionInit();
extern void ApplifierCrossPromotionTerminate();


#if defined I3D_OS_IPHONE || defined I3D_OS_OSX

static s3eResult init_wrap(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: init"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)init, 5, applifierID, orientationHomeButtonDown, orientationHomeButtonRight, orientationHomeButtonLeft, orientationHomeButtonUp);
}

static bool showBanner_wrap(int positionX, int positionY)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: showBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)showBanner, 2, positionX, positionY);
}

static bool hideBanner_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: hideBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)hideBanner, 0);
}

static bool prepareFeaturedGames_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: prepareFeaturedGames"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)prepareFeaturedGames, 0);
}

static bool prepareInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: prepareInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)prepareInterstitial, 0);
}

static bool isFeaturedGamesReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: isFeaturedGamesReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)isFeaturedGamesReady, 0);
}

static bool isInterstitialReady_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: isInterstitialReady"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)isInterstitialReady, 0);
}

static bool showFeaturedGames_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: showFeaturedGames"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)showFeaturedGames, 0);
}

static bool showInterstitial_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: showInterstitial"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)showInterstitial, 0);
}

static bool pauseRenderer_wrap()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: pauseRenderer"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)pauseRenderer, 0);
}

static bool moveBanner_wrap(int x, int y)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion func on main thread: moveBanner"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)moveBanner, 2, x, y);
}

#define init init_wrap
#define showBanner showBanner_wrap
#define hideBanner hideBanner_wrap
#define prepareFeaturedGames prepareFeaturedGames_wrap
#define prepareInterstitial prepareInterstitial_wrap
#define isFeaturedGamesReady isFeaturedGamesReady_wrap
#define isInterstitialReady isInterstitialReady_wrap
#define showFeaturedGames showFeaturedGames_wrap
#define showInterstitial showInterstitial_wrap
#define pauseRenderer pauseRenderer_wrap
#define moveBanner moveBanner_wrap

#endif /* I3D_OS_IPHONE */

void ApplifierCrossPromotionRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[11];
    funcPtrs[0] = (void*)init;
    funcPtrs[1] = (void*)showBanner;
    funcPtrs[2] = (void*)hideBanner;
    funcPtrs[3] = (void*)prepareFeaturedGames;
    funcPtrs[4] = (void*)prepareInterstitial;
    funcPtrs[5] = (void*)isFeaturedGamesReady;
    funcPtrs[6] = (void*)isInterstitialReady;
    funcPtrs[7] = (void*)showFeaturedGames;
    funcPtrs[8] = (void*)showInterstitial;
    funcPtrs[9] = (void*)pauseRenderer;
    funcPtrs[10] = (void*)moveBanner;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[11] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("ApplifierCrossPromotion", funcPtrs, sizeof(funcPtrs), flags, ApplifierCrossPromotionInit, ApplifierCrossPromotionTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int ApplifierCrossPromotionStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&ApplifierCrossPromotionRegisterExt;
    return 0;
}

int g_ApplifierCrossPromotionVal = ApplifierCrossPromotionStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    ApplifierCrossPromotionRegisterExt();
}
#endif

#endif
