/*
 * Copyright (C) 2001-2011 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_APPLIFIERCROSSPROMOTION_H
#define S3E_EXT_APPLIFIERCROSSPROMOTION_H

#include <s3eTypes.h>

S3E_BEGIN_C_DECL

/**
 * Returns S3E_TRUE if the ApplifierCrossPromotion extension is available.
 */
s3eBool ApplifierCrossPromotionAvailable();

s3eResult init(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp);

bool showBanner(int positionX, int positionY);

bool hideBanner();

bool prepareFeaturedGames();

bool prepareInterstitial();

bool isFeaturedGamesReady();

bool isInterstitialReady();

bool showFeaturedGames();

bool showInterstitial();

bool pauseRenderer();

S3E_END_C_DECL

#endif /* !S3E_EXT_APPLIFIERCROSSPROMOTION_H */
