/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "ApplifierCrossPromotion.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*ApplifierCrossPromotionInitialize_t)(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp);
typedef       bool(*ApplifierCrossPromotionShowBanner_t)(int positionX, int positionY);
typedef       bool(*ApplifierCrossPromotionHideBanner_t)();
typedef       bool(*ApplifierCrossPromotionPrepareFeaturedGames_t)();
typedef       bool(*ApplifierCrossPromotionPrepareInterstitial_t)();
typedef       bool(*ApplifierCrossPromotionIsFeaturedGamesReady_t)();
typedef       bool(*ApplifierCrossPromotionIsInterstitialReady_t)();
typedef       bool(*ApplifierCrossPromotionShowFeaturedGames_t)();
typedef       bool(*ApplifierCrossPromotionShowInterstitial_t)();
typedef       bool(*ApplifierCrossPromotionPauseRenderer_t)();
typedef       bool(*ApplifierCrossPromotionMoveBanner_t)(int x, int y);

/**
 * struct that gets filled in by ApplifierCrossPromotionRegister
 */
typedef struct ApplifierCrossPromotionFuncs
{
    ApplifierCrossPromotionInitialize_t m_ApplifierCrossPromotionInitialize;
    ApplifierCrossPromotionShowBanner_t m_ApplifierCrossPromotionShowBanner;
    ApplifierCrossPromotionHideBanner_t m_ApplifierCrossPromotionHideBanner;
    ApplifierCrossPromotionPrepareFeaturedGames_t m_ApplifierCrossPromotionPrepareFeaturedGames;
    ApplifierCrossPromotionPrepareInterstitial_t m_ApplifierCrossPromotionPrepareInterstitial;
    ApplifierCrossPromotionIsFeaturedGamesReady_t m_ApplifierCrossPromotionIsFeaturedGamesReady;
    ApplifierCrossPromotionIsInterstitialReady_t m_ApplifierCrossPromotionIsInterstitialReady;
    ApplifierCrossPromotionShowFeaturedGames_t m_ApplifierCrossPromotionShowFeaturedGames;
    ApplifierCrossPromotionShowInterstitial_t m_ApplifierCrossPromotionShowInterstitial;
    ApplifierCrossPromotionPauseRenderer_t m_ApplifierCrossPromotionPauseRenderer;
    ApplifierCrossPromotionMoveBanner_t m_ApplifierCrossPromotionMoveBanner;
} ApplifierCrossPromotionFuncs;

static ApplifierCrossPromotionFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xbf725632, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: ApplifierCrossPromotion");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xbf725632, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool ApplifierCrossPromotionAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult ApplifierCrossPromotionInitialize(const char* applifierID, bool orientationHomeButtonDown, bool orientationHomeButtonRight, bool orientationHomeButtonLeft, bool orientationHomeButtonUp)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[0] func: ApplifierCrossPromotionInitialize"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_ApplifierCrossPromotionInitialize(applifierID, orientationHomeButtonDown, orientationHomeButtonRight, orientationHomeButtonLeft, orientationHomeButtonUp);
}

bool ApplifierCrossPromotionShowBanner(int positionX, int positionY)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[1] func: ApplifierCrossPromotionShowBanner"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionShowBanner(positionX, positionY);
}

bool ApplifierCrossPromotionHideBanner()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[2] func: ApplifierCrossPromotionHideBanner"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionHideBanner();
}

bool ApplifierCrossPromotionPrepareFeaturedGames()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[3] func: ApplifierCrossPromotionPrepareFeaturedGames"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionPrepareFeaturedGames();
}

bool ApplifierCrossPromotionPrepareInterstitial()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[4] func: ApplifierCrossPromotionPrepareInterstitial"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionPrepareInterstitial();
}

bool ApplifierCrossPromotionIsFeaturedGamesReady()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[5] func: ApplifierCrossPromotionIsFeaturedGamesReady"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionIsFeaturedGamesReady();
}

bool ApplifierCrossPromotionIsInterstitialReady()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[6] func: ApplifierCrossPromotionIsInterstitialReady"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionIsInterstitialReady();
}

bool ApplifierCrossPromotionShowFeaturedGames()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[7] func: ApplifierCrossPromotionShowFeaturedGames"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionShowFeaturedGames();
}

bool ApplifierCrossPromotionShowInterstitial()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[8] func: ApplifierCrossPromotionShowInterstitial"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionShowInterstitial();
}

bool ApplifierCrossPromotionPauseRenderer()
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[9] func: ApplifierCrossPromotionPauseRenderer"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionPauseRenderer();
}

bool ApplifierCrossPromotionMoveBanner(int x, int y)
{
    IwTrace(APPLIFIERCROSSPROMOTION_VERBOSE, ("calling ApplifierCrossPromotion[10] func: ApplifierCrossPromotionMoveBanner"));

    if (!_extLoad())
        return false;

    return g_Ext.m_ApplifierCrossPromotionMoveBanner(x, y);
}
